# Generated by Django 4.1 on 2022-08-25 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('ID_ADHERENT', models.BigIntegerField(primary_key=True, serialize=False)),
                ('NOM_PRENOM_RS', models.CharField(max_length=255, null=True)),
                ('CODE_DIRECTION', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('ID_DECLARATION', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ID_ENVOI_EDI', models.BigIntegerField(blank=True)),
                ('ID_FORMULAIRE', models.IntegerField()),
                ('ANNEE_DECLAR', models.IntegerField()),
                ('PERIODE_DECLAR', models.SmallIntegerField()),
                ('REGIME_DECLAR', models.SmallIntegerField()),
                ('CODE_COMP', models.IntegerField(blank=True)),
                ('DATE_DEPOT', models.DateField()),
                ('FAIT_GEN', models.CharField(max_length=255)),
                ('RENS', models.CharField(max_length=1024)),
                ('MODE_DECLAR', models.SmallIntegerField()),
                ('CA_GLOBAL', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MNT_TAXE', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MNT_DEDUCTION', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MNT_CREDIT', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TVA_DUE', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PAIEMENT_ACCOMP', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TAXE_PAYEE', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ETAT_DECLARATION', models.IntegerField()),
                ('RELEVE_DEDUCTION', models.CharField(max_length=100)),
                ('DATE_EFF_DEPOT', models.DateField()),
                ('IS_HISTORY_ONLY', models.SmallIntegerField(default=0)),
                ('TYPE_DECLAR', models.CharField(max_length=255)),
                ('DELETED', models.SmallIntegerField(default=10)),
                ('USER_MAJ', models.CharField(max_length=100)),
                ('DATE_MAJ', models.DateTimeField(auto_now_add=True)),
                ('DATE_TRANSFERT_METIER', models.DateField()),
                ('MAJ', models.CharField(max_length=1)),
                ('MAJ_T_METIER', models.CharField(max_length=1)),
                ('RELEVE_DEDUCTION_AUTRE', models.CharField(max_length=100)),
                ('PAIEMENT_MC_INITILIZED', models.SmallIntegerField(default=0)),
                ('REF_PAIEMENT', models.CharField(max_length=20)),
                ('MONTANT_VERSE', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PRINCIPAL_VERSE', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('DROITS_COMP_TVA', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ID_ADHERENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.adherent')),
            ],
        ),
        migrations.CreateModel(
            name='Form_TVA',
            fields=[
                ('ID_FORMULAIRE', models.IntegerField(primary_key=True, serialize=False)),
                ('ANNEE_FORMULAIRE', models.IntegerField(null=True)),
                ('LIB_FORMULAIRE', models.CharField(max_length=255, null=True)),
                ('DATE_CREATION_FORM', models.DateField(auto_now_add=True, null=True)),
                ('PUBLICATION_FORMULAIRE', models.SmallIntegerField(null=True)),
                ('CLASS_NAME', models.CharField(default='', max_length=255)),
                ('DATE_TRANSFERT_METIER', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Releve_deduction_edi',
            fields=[
                ('ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('NUM_ORDRE', models.BigIntegerField()),
                ('NUM_FACTURE', models.CharField(max_length=250)),
                ('DATE_FACTURE', models.DateField()),
                ('MONTANT_HT', models.FloatField()),
                ('MONTANT_TVA', models.FloatField()),
                ('MONTANT_TTC', models.FloatField()),
                ('TAUX', models.FloatField()),
                ('REF_MODE_PAIEMENT', models.BigIntegerField()),
                ('DATE_PAIEMENT', models.DateField()),
                ('ID_DECLARATION', models.BigIntegerField()),
                ('NOM_FOURNISSEUR', models.CharField(max_length=250)),
                ('IF_FOURNISSEUR', models.CharField(max_length=8)),
                ('ICE_FOURNISSEUR', models.CharField(max_length=16)),
                ('ID_TRACE', models.BigIntegerField()),
                ('PRORATA', models.FloatField()),
                ('MONTANT_TVA_PRORATA', models.FloatField()),
                ('DATE_TRANSFERT_METIER', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Releve_Deduction',
            fields=[
                ('ID_DECLARATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MyApp.declaration')),
                ('RELEVE_DEDUCTION', models.FileField(upload_to='')),
                ('IS_VALID', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TYPE_TAUX',
            fields=[
                ('ID_TYPE_TAUX', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('TYPE_TAUX', models.CharField(max_length=255, null=True)),
                ('LIB_TYPE_TAUX', models.CharField(max_length=100, null=True)),
                ('TAUX_NORMAL', models.SmallIntegerField(null=True)),
                ('TAUX_AVEC_DEDUCTION', models.SmallIntegerField(null=True)),
                ('LIB_TYPE_TAUX_AR', models.CharField(max_length=255, null=True)),
                ('ID_FORMULAIRE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.form_tva')),
            ],
        ),
        migrations.CreateModel(
            name='TYPE_DEDUCTION',
            fields=[
                ('ID_TYPE_DEDUCTION', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('TYPE_DEDUCTION', models.CharField(max_length=255)),
                ('LIB_TYPE_DEDUCTION', models.CharField(max_length=100, null=True)),
                ('ORDRE', models.IntegerField(null=True)),
                ('LIB_TYPE_DEDUCTION_AR', models.CharField(max_length=255, null=True)),
                ('ID_FORMULAIRE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.form_tva')),
            ],
        ),
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('ID_RUBRIQUE', models.BigIntegerField(primary_key=True, serialize=False)),
                ('CODE_RUBRIQUE', models.IntegerField(default=10)),
                ('LIB_RUBRIQUE', models.CharField(max_length=255, null=True)),
                ('PRECISION_RUBRIQUE', models.CharField(max_length=1024, null=True)),
                ('TAUX_RUBRIQUE', models.DecimalField(decimal_places=3, max_digits=15, null=True)),
                ('ORDER_RUBRIQUE', models.IntegerField(null=True)),
                ('LIB_RUBRIQUE_AR', models.CharField(max_length=500, null=True)),
                ('ID_TYPE_DEDUCTION', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.type_deduction')),
                ('ID_TYPE_TAUX', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.type_taux')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('ID_DESIGNATION', models.BigIntegerField(primary_key=True, serialize=False)),
                ('MONTANT_HT', models.FloatField()),
                ('MONTANT_TTC', models.FloatField()),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.releve_deduction_edi')),
            ],
        ),
        migrations.CreateModel(
            name='CA_Total',
            fields=[
                ('ID_CA_TOTAL', models.BigIntegerField(primary_key=True, serialize=False)),
                ('CODE_CA_TOTAL', models.IntegerField()),
                ('LIB_CA_TOTAL', models.CharField(max_length=255)),
                ('PRECISION_CA_TOTAL', models.CharField(max_length=1024)),
                ('LIB_CA_TOTAL_AR', models.CharField(max_length=255)),
                ('ID_FORMULAIRE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.form_tva')),
            ],
        ),
        migrations.CreateModel(
            name='Taxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BASE_IMPOSABLE', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TAXE_EXIGIBLE', models.DecimalField(decimal_places=2, max_digits=15)),
                ('USED', models.SmallIntegerField(default=0)),
                ('ID_DECLARATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.declaration')),
                ('ID_RUBRIQUE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.rubrique')),
            ],
            options={
                'unique_together': {('ID_DECLARATION', 'ID_RUBRIQUE')},
            },
        ),
        migrations.CreateModel(
            name='Montant_CA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MNT_CA', models.DecimalField(decimal_places=2, max_digits=15)),
                ('USED', models.SmallIntegerField(default=0)),
                ('ID_CA_TOTAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.ca_total')),
                ('ID_DECLARATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.declaration')),
            ],
            options={
                'unique_together': {('ID_CA_TOTAL', 'ID_DECLARATION')},
            },
        ),
        migrations.CreateModel(
            name='Montant_Bilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_BILAN', models.BigIntegerField()),
                ('MNT_BILAN', models.DecimalField(decimal_places=2, max_digits=15)),
                ('USED', models.SmallIntegerField(default=0)),
                ('ID_DECLARATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.declaration')),
            ],
            options={
                'unique_together': {('ID_BILAN', 'ID_DECLARATION')},
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TVA_FACTURES', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TVA_DEDUCTIBL', models.FloatField()),
                ('APPLIQUE_PRORATA', models.DecimalField(decimal_places=2, max_digits=15)),
                ('USED', models.SmallIntegerField(default=0)),
                ('ID_DECLARATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.declaration')),
                ('ID_RUBRIQUE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.rubrique')),
            ],
            options={
                'unique_together': {('ID_DECLARATION', 'ID_RUBRIQUE')},
            },
        ),
    ]
