# Generated by Django 4.1 on 2022-08-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='ID',
            new_name='ID_RELEVE',
        ),
    ]
