# Generated by Django 4.1 on 2022-08-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_rename_id_designation_id_releve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaration',
            name='CODE_COMP',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='DATE_EFF_DEPOT',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='DATE_MAJ',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='DATE_TRANSFERT_METIER',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='DELETED',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='DROITS_COMP_TVA',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='ETAT_DECLARATION',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='FAIT_GEN',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='IS_HISTORY_ONLY',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='MAJ',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='MAJ_T_METIER',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='MODE_DECLAR',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='MONTANT_VERSE',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='PAIEMENT_MC_INITILIZED',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='PERIODE_DECLAR',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='PRINCIPAL_VERSE',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='REF_PAIEMENT',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='REGIME_DECLAR',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='RELEVE_DEDUCTION',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='RELEVE_DEDUCTION_AUTRE',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='RENS',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='TYPE_DECLAR',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='USER_MAJ',
        ),
    ]
