# Generated by Django 4.1 on 2022-08-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_remove_declaration_code_comp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releve_deduction_edi',
            name='DATE_FACTURE',
        ),
        migrations.RemoveField(
            model_name='releve_deduction_edi',
            name='DATE_PAIEMENT',
        ),
        migrations.RemoveField(
            model_name='releve_deduction_edi',
            name='DATE_TRANSFERT_METIER',
        ),
        migrations.RemoveField(
            model_name='releve_deduction_edi',
            name='ICE_FOURNISSEUR',
        ),
        migrations.RemoveField(
            model_name='releve_deduction_edi',
            name='ID_TRACE',
        ),
        migrations.RemoveField(
            model_name='releve_deduction_edi',
            name='IF_FOURNISSEUR',
        ),
        migrations.RemoveField(
            model_name='releve_deduction_edi',
            name='MONTANT_TVA_PRORATA',
        ),
        migrations.RemoveField(
            model_name='releve_deduction_edi',
            name='NOM_FOURNISSEUR',
        ),
        migrations.RemoveField(
            model_name='releve_deduction_edi',
            name='NUM_FACTURE',
        ),
        migrations.RemoveField(
            model_name='releve_deduction_edi',
            name='NUM_ORDRE',
        ),
        migrations.RemoveField(
            model_name='releve_deduction_edi',
            name='PRORATA',
        ),
        migrations.RemoveField(
            model_name='releve_deduction_edi',
            name='REF_MODE_PAIEMENT',
        ),
        migrations.RemoveField(
            model_name='releve_deduction_edi',
            name='TAUX',
        ),
    ]
