# Generated by Django 4.1 on 2022-08-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_remove_releve_deduction_edi_date_facture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='Designation',
            field=models.CharField(default='', max_length=255),
        ),
    ]
